name: Stats

on:
  push:
    branches:
      - master

jobs:
  stats:
    env:
      branch: ci-stats
    runs-on: ubuntu-20.04
    steps:
      - name: '❄ Wait for Hydra build'
        uses: rvl/hydra-build-products-action@master
        id: hydra
        with:
          hydra: https://hydra.iohk.io
          statusName: ci/hydra-eval
          jobs: required
          requiredJob: required
          project: Cardano
          jobset: cardano-wallet
        timeout-minutes: 180

      - name: '📥 Checkout Code'
        uses: actions/checkout@v3.2

      - name: '📥 Checkout Stats'
        uses: actions/checkout@v3.2
        with:
          ref: ${{ env.branch }}
          fetch-depth: 1
          path: _build

      - name: '📘 Publish Stats'
        working-directory: _build
        run: |
          echo '${{ steps.hydra.outputs.evaluation }}' > eval.json
          echo '${{ steps.hydra.outputs.builds }}' > builds.json
          echo '${{ steps.hydra.outputs.timings }}' > timings.json
          ../scripts/gh/update-stats.sh '${{ env.branch}}' eval.json builds.json timings.json
