name: Docker-compose Linux
on:
  schedule:
  - cron:  "0 23 * * *"
  workflow_dispatch:
    inputs:
      network:
        description: 'NETWORK'
        required: true
        default: 'mainnet'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ruby/setup-ruby@v1.127.0
        with:
          ruby-version: 2.7.1
      - name: Install cardano_wallet gem
        run: gem install cardano_wallet
      - name: Check docker-compose
        run: |
          docker-compose up -d
          ./scripts/connect_wallet.rb
        env:
          NETWORK: ${{ github.event.inputs.network || 'mainnet' }}
