name: E2E MacOS --light

on:
  schedule:
  - cron:  "0 22 * * *"
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'testnet'
      pr:
        description: 'PR number or "master"'
        default: 'master'

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Prepare MacOS
      run: brew install screen

    - name: 🕒 Get Date/Time
      id: date-time
      shell: bash
      run: |
        echo "::set-output name=value::$(rake datetime)"

    - name: ⚙️ Setup (get latest bins and configs and decode fixtures)
      run: rake setup[$NETWORK,$PR]

    - name: 🔍 Display versions
      run: rake display_versions

    - name: 🚀 Start wallet --light
      run: rake start_wallet_light[$NETWORK]

    - name: 🧪 Run all tests
      run: rake spec SPEC_OPTS="-t light"

    - name: 🏁 Stop wallet --light
      run: rake stop_wallet_light[$NETWORK]

    - name: 📎 Upload logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ runner.os }}-logs
        path: test/e2e/state/logs

    env:
      TESTS_E2E_FIXTURES: ${{ secrets.TESTS_E2E_FIXTURES }}
      NETWORK: ${{ github.event.inputs.network || 'testnet' }}
      PR: ${{ github.event.inputs.pr || '' }}
