name: Rubocop

on:
  push:
    branches: [ "master" ]
    paths: ['test/e2e/**']
  pull_request:
    branches: [ "master" ]
    paths: ['test/e2e/**']

permissions:
  contents: read

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  rubocop-linter:
    runs-on: ubuntu-latest

    steps:
    - name: '📥 Checkout repository'
      uses: actions/checkout@v3.2.0

    - name: 💎 Set up Ruby
      uses: ruby/setup-ruby@v1.127.0
      with:
        ruby-version: 3.1.2
        bundler-cache: true

    - name: 👮 Rubocop
      run: |
        gem install rubocop
        rubocop
