name: windows

on:
  schedule:
  - cron:  "0 20 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Run tests against branch'
        default: 'master'

jobs:
  setup:
    env:
      BUILDKITE_API_TOKEN: ${{ secrets.BUILDKITE_TOKEN_READ_BUILDS_ARTIFACTS }}
      WORK_DIR: ./test/e2e
      BRANCH: ${{ github.event.inputs.branch || 'master' }}
    runs-on: windows-2022
    name: Download testing bundle
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.127.0
        with:
          ruby-version: 2.7.1
          bundler-cache: true

      - name: Get 'cardano-wallet-tests-win64.zip'
        working-directory: ${{ env.WORK_DIR }}
        run: |
          bundle install
          rake get_latest_windows_tests[%BRANCH%,cardano-wallet-tests-win64]

      - name: Report version
        working-directory: ${{ env.WORK_DIR }}
        run: rake display_versions[cardano-wallet-tests-win64]

      - name: Save files
        uses: actions/upload-artifact@v3
        with:
          name: cardano-wallet-tests-win64
          path: ${{ env.WORK_DIR }}/cardano-wallet-tests-win64

  cardano-wallet-test-unit:
    name: 'cardano-wallet:unit'
    needs: setup
    runs-on: windows-2022
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-test-unit.exe --color --jobs 1 --skip /Cardano.Wallet.DB.Sqlite/ +RTS -M2G -N2'

  text-class-test-unit:
    name: 'test-class:unit'
    needs: setup
    runs-on: windows-2022
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\text-class-test-unit.exe --color'

  cardano-wallet-launcher-test-unit:
    name: 'cardano-wallet-launcher:unit'
    needs: setup
    runs-on: windows-2022
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cardano-wallet-tests-win64
      - run: '.\\cardano-wallet-launcher-test-unit.exe --color'
        continue-on-error: true

  # ADP-2517 - Fix integration tests on Windows
  # cardano-wallet-test-integration:
  #   name: 'cardano-wallet:integration'
  #   needs: setup
  #   runs-on: windows-2022
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: cardano-wallet-tests-win64
  #     - run: '.\\cardano-wallet-test-integration.exe --color'
  #       timeout-minutes: 60
